language: ruby
services:
  - postgresql
rvm:
  - 2.2.0
env:
  - DB=postgresql
before_script:
  - psql -c 'create database T2_development;' -U postgres
  - psql -c 'create database T2_testing;' -U postgres
  - psql -c 'create database T2_production;' -U postgres   
script: 
  - bundle exec rake db:create --trace
  - bundle exec rake db:migrate --trace
  - RAILS_ENV=test bundle exec rake db:create --trace
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - RAILS_ENV=test bundle exec rake db:seed --trace  
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec
  - bundle exec rake my_namespace:update_version
#  - bundle exec rspec spec/
bundler_args: --binstubs=./bundler_stubs
#after_success:
deploy:
  provider: heroku
  api_key: 437a311a-23c6-4303-bb04-4b415dc40f32
  app: integrat2enzozerega
  run: "rake my_namespace:update_version"
